# ~1B parameters — LLaMA-3.2 (same family as DiffuLLaMA, ICLR 2025)
# Gated model: requires HF_TOKEN with Meta license acceptance
# GQA (8 KV heads) works correctly with the 4D bidirectional mask
model_name_or_path: meta-llama/Llama-3.2-1B
init_from_pretrained: true
attn_implementation: eager   # use flash_attention_2 on GPU
dtype: float32               # use bfloat16 on GPU
use_lora: false
